[19-Mar-2025 13:30:53 Europe/Berlin] SQLSTATE[HY000] [2002] Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot
[19-Mar-2025 13:30:53 Europe/Berlin] PHP Fatal error:  Uncaught RuntimeException: Database connection error. in C:\xampp\htdocs\school-oop\app\Database\Database.php:36
Stack trace:
#0 C:\xampp\htdocs\school-oop\app\Database\Database.php(43): App\Database\Database->__construct(Array)
#1 C:\xampp\htdocs\school-oop\app\Models\Model.php(17): App\Database\Database::getInstance()
#2 C:\xampp\htdocs\school-oop\app\Models\Subject.php(13): App\Models\Model->__construct()
#3 C:\xampp\htdocs\school-oop\app\Controllers\SubjectController.php(10): App\Models\Subject->__construct()
#4 C:\xampp\htdocs\school-oop\app\Routing\Router.php(49): App\Controllers\SubjectController->__construct()
#5 C:\xampp\htdocs\school-oop\app\Routing\Router.php(26): App\Routing\Router->handleGetRequests('/subjects')
#6 C:\xampp\htdocs\school-oop\app\Routing\Router.php(19): App\Routing\Router->dispatch('GET', '/subjects')
#7 C:\xampp\htdocs\school-oop\public\index.php(24): App\Routing\Router->handle()
#8 {main}
  thrown in C:\xampp\htdocs\school-oop\app\Database\Database.php on line 36
